// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListServer.Database;

namespace ShoppingListServer.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20220108143748_AddEMailVerification")]
    partial class AddEMailVerification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasCharSet(null, DelegationModes.ApplyToAll)
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ShoppingListServer.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Salt")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShoppingListServer.Models.EMailVerificationToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UrlCode")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EMailVerificationToken");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingData.ShoppingListPermission", b =>
                {
                    b.Property<string>("ShoppingListId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("ShoppingListId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingListPermission");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingList", b =>
                {
                    b.Property<string>("SyncId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("SyncId");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("ShoppingListServer.Models.EMailVerificationToken", b =>
                {
                    b.HasOne("ShoppingListServer.Entities.User", "User")
                        .WithMany("EMailVerificationTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingData.ShoppingListPermission", b =>
                {
                    b.HasOne("ShoppingListServer.Models.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListPermissions")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppingListServer.Entities.User", "User")
                        .WithMany("ShoppingListPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoppingListServer.Entities.User", b =>
                {
                    b.Navigation("EMailVerificationTokens");

                    b.Navigation("ShoppingListPermissions");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
