// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListServer.Database;

#nullable disable

namespace ShoppingListServer.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20220712112604_AddImageInfo")]
    partial class AddImageInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, null, DelegationModes.ApplyToAll);

            modelBuilder.Entity("ShoppingListServer.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ColorArgb")
                        .HasColumnType("int");

                    b.Property<string>("ContactShareIdId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext");

                    b.Property<string>("FcmToken")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePictureInfoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Salt")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactShareIdId");

                    b.HasIndex("ProfilePictureInfoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShoppingListServer.Models.EMailVerificationToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UrlCode")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EMailVerificationToken");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ExpirationToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ExpirationToken");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ImageInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastChangeImageFileTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastChangeTransformationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Rotation")
                        .HasColumnType("double");

                    b.Property<double>("Scale")
                        .HasColumnType("double");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImageInfo");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ResetPasswordToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ResetPasswordToken");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingData.ShoppingListPermission", b =>
                {
                    b.Property<string>("ShoppingListId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("ShoppingListId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingListPermission");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingList", b =>
                {
                    b.Property<string>("SyncId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastChangeServerTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ShareIdId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("SyncId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ShareIdId");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("ShoppingListServer.Models.UserContact", b =>
                {
                    b.Property<string>("UserSourceId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserTargetId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserContactType")
                        .HasColumnType("int");

                    b.HasKey("UserSourceId", "UserTargetId");

                    b.HasIndex("UserTargetId");

                    b.ToTable("UserContact");
                });

            modelBuilder.Entity("ShoppingListServer.Entities.User", b =>
                {
                    b.HasOne("ShoppingListServer.Models.ExpirationToken", "ContactShareId")
                        .WithMany()
                        .HasForeignKey("ContactShareIdId");

                    b.HasOne("ShoppingListServer.Models.ImageInfo", "ProfilePictureInfo")
                        .WithMany()
                        .HasForeignKey("ProfilePictureInfoId");

                    b.Navigation("ContactShareId");

                    b.Navigation("ProfilePictureInfo");
                });

            modelBuilder.Entity("ShoppingListServer.Models.EMailVerificationToken", b =>
                {
                    b.HasOne("ShoppingListServer.Entities.User", "User")
                        .WithMany("EMailVerificationTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ResetPasswordToken", b =>
                {
                    b.HasOne("ShoppingListServer.Entities.User", "User")
                        .WithMany("ResetPasswordTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingData.ShoppingListPermission", b =>
                {
                    b.HasOne("ShoppingListServer.Models.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListPermissions")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppingListServer.Entities.User", "User")
                        .WithMany("ShoppingListPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingList", b =>
                {
                    b.HasOne("ShoppingListServer.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("ShoppingListServer.Models.ExpirationToken", "ShareId")
                        .WithMany()
                        .HasForeignKey("ShareIdId");

                    b.Navigation("Owner");

                    b.Navigation("ShareId");
                });

            modelBuilder.Entity("ShoppingListServer.Models.UserContact", b =>
                {
                    b.HasOne("ShoppingListServer.Entities.User", "UserSource")
                        .WithMany("UserContactsThis")
                        .HasForeignKey("UserSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppingListServer.Entities.User", "UserTarget")
                        .WithMany("UserContactsOthers")
                        .HasForeignKey("UserTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSource");

                    b.Navigation("UserTarget");
                });

            modelBuilder.Entity("ShoppingListServer.Entities.User", b =>
                {
                    b.Navigation("EMailVerificationTokens");

                    b.Navigation("ResetPasswordTokens");

                    b.Navigation("ShoppingListPermissions");

                    b.Navigation("UserContactsOthers");

                    b.Navigation("UserContactsThis");
                });

            modelBuilder.Entity("ShoppingListServer.Models.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
