apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shopping-list-server
  namespace: shopping-list
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shopping-list-server
