apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: shopping-list
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-data
  namespace: shopping-list
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
